#defaults:
hydra:
  run:
    dir: ./
model:
  pretrained: true
  out_dim: 1
  in_dim: 2048
max_epochs: 100
stopping_patience: 10
training:
  optimizer:
    name: adam
    lr: 0.0003
  scheduler:
    monitor: val_loss
    mode: min
    name: plateau
    patience: 5
    min_lr: 0.00001
    factor: 0.5
data:
  size: 32
  batch_size: 64